# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'voltmeter.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qwt import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(428, 297)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Dial = QwtDial(self.centralwidget)
        self.Dial.setGeometry(QtCore.QRect(30, 20, 200, 231))
        self.Dial.setUpperBound(3.3)
        self.Dial.setProperty("value", 1.5)
        self.Dial.setLineWidth(4)
        self.Dial.setOrigin(180.0)
        self.Dial.setMaxScaleArc(180.0)
        self.Dial.setObjectName("Dial")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(60, 160, 131, 41))
        self.lcdNumber.setDigitCount(4)
        self.lcdNumber.setObjectName("lcdNumber")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(250, 20, 163, 111))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.ip_address_text = QtWidgets.QLineEdit(self.widget)
        self.ip_address_text.setObjectName("ip_address_text")
        self.verticalLayout.addWidget(self.ip_address_text)
        self.connect_pb = QtWidgets.QPushButton(self.widget)
        self.connect_pb.setObjectName("connect_pb")
        self.verticalLayout.addWidget(self.connect_pb)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 428, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Uli's Voltmeter", "Uli's Voltmeter"))
        self.label.setText(_translate("MainWindow", "IP address of Voltmeter\n"
"Server"))
        self.ip_address_text.setText(_translate("MainWindow", "192.168.0.xxx"))
        self.connect_pb.setText(_translate("MainWindow", "Connect to Server"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))

