# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'oscilloscope.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(703, 369)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.trigger_slope_label = QtWidgets.QLabel(self.centralwidget)
        self.trigger_slope_label.setGeometry(QtCore.QRect(600, 60, 91, 17))
        self.trigger_slope_label.setObjectName("trigger_slope_label")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 30, 535, 258))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.oscilloscope_screen = QtChart.QChartView(self.layoutWidget)
        self.oscilloscope_screen.setFrameShape(QtWidgets.QFrame.Panel)
        self.oscilloscope_screen.setObjectName("oscilloscope_screen")
        self.horizontalLayout.addWidget(self.oscilloscope_screen)
        self.verticalSlider = QtWidgets.QSlider(self.layoutWidget)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.horizontalLayout.addWidget(self.verticalSlider)
        self.trigger_slop_pb = QtWidgets.QPushButton(self.centralwidget)
        self.trigger_slop_pb.setGeometry(QtCore.QRect(600, 90, 71, 41))
        self.trigger_slop_pb.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("risingEdge.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("fallingEdge.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.trigger_slop_pb.setIcon(icon)
        self.trigger_slop_pb.setIconSize(QtCore.QSize(48, 48))
        self.trigger_slop_pb.setCheckable(True)
        self.trigger_slop_pb.setObjectName("trigger_slop_pb")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 703, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionquit = QtWidgets.QAction(MainWindow)
        self.actionquit.setObjectName("actionquit")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionquit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Uli\'s Oscilloscope"))
        self.trigger_slope_label.setText(_translate("MainWindow", "Trigger slope"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionquit.setText(_translate("MainWindow", "Quit"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
from PyQt5 import QtChart


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
